"""empty message

Revision ID: 839e7e9da974
Revises: 
Create Date: 2020-04-26 23:01:33.412473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '839e7e9da974'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('bio', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('confirmed', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('location', sa.String(), nullable=True))
    op.add_column('user', sa.Column('member_since', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('name', sa.String(length=30), nullable=True))
    op.add_column('user', sa.Column('website', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'website')
    op.drop_column('user', 'name')
    op.drop_column('user', 'member_since')
    op.drop_column('user', 'location')
    op.drop_column('user', 'confirmed')
    op.drop_column('user', 'bio')
    # ### end Alembic commands ###
